// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53I1jn42IBUdsvjxPELKAcL3Z2lGlwuI',
    appId: '1:964050515073:web:d1d3705fb0f944fc7cc980',
    messagingSenderId: '964050515073',
    projectId: 'littlebird-e0122',
    authDomain: 'littlebird-e0122.firebaseapp.com',
    storageBucket: 'littlebird-e0122.firebasestorage.app',
    measurementId: 'G-XSYTFYH3XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfrCXZjHxVUQuZku1asoqQEUG63B-UCv0',
    appId: '1:964050515073:android:24771888af5419cd7cc980',
    messagingSenderId: '964050515073',
    projectId: 'littlebird-e0122',
    storageBucket: 'littlebird-e0122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCmYKQC93NqACBn-Axxw24BMvgb0DwaxA',
    appId: '1:964050515073:ios:bff221837fd37cf17cc980',
    messagingSenderId: '964050515073',
    projectId: 'littlebird-e0122',
    storageBucket: 'littlebird-e0122.firebasestorage.app',
    iosClientId: '964050515073-emtvs0tnsik01l7gsm8j8oftho5u6l9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlebird',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCmYKQC93NqACBn-Axxw24BMvgb0DwaxA',
    appId: '1:964050515073:ios:bff221837fd37cf17cc980',
    messagingSenderId: '964050515073',
    projectId: 'littlebird-e0122',
    storageBucket: 'littlebird-e0122.firebasestorage.app',
    iosClientId: '964050515073-emtvs0tnsik01l7gsm8j8oftho5u6l9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.littlebird',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB53I1jn42IBUdsvjxPELKAcL3Z2lGlwuI',
    appId: '1:964050515073:web:42b55ad51bbc6e627cc980',
    messagingSenderId: '964050515073',
    projectId: 'littlebird-e0122',
    authDomain: 'littlebird-e0122.firebaseapp.com',
    storageBucket: 'littlebird-e0122.firebasestorage.app',
    measurementId: 'G-60J0B3VDNW',
  );
}
