import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is generated by `flutterfire configure`
import 'auth/auth_wrapper.dart'; // Import the new auth wrapper

Future<void> main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const LittlebirdApp());
}

class LittlebirdApp extends StatelessWidget {
  const LittlebirdApp({super.key});

  @override
  Widget build(BuildContext context) {
    final colorScheme = ColorScheme.fromSeed(
      seedColor: Colors.blue, // Your app's brand color
      brightness: Brightness.dark,
    );

    return MaterialApp(
      title: 'Littlebird',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: colorScheme,
        useMaterial3: true,
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF121212),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF1E1E1E),
          elevation: 0,
        ),
        cardColor: const Color(0xFF1E1E1E),
        floatingActionButtonTheme: FloatingActionButtonThemeData(
          backgroundColor: colorScheme.primary,
          foregroundColor: colorScheme.onPrimary,
        ),

        // --- AESTHETIC UPGRADE: Minimalist NavigationBar Theme ---
        navigationBarTheme: NavigationBarThemeData(
          // Flat, modern look
          elevation: 0,
          // Set the background color
          backgroundColor: colorScheme.surfaceContainer,
          // This tints the background color slightly, blending with content
          surfaceTintColor: colorScheme.surfaceContainer,

          // Make the indicator pill INVISIBLE
          indicatorColor: Colors.transparent,

          // Make the SELECTED icon use your primary color
          iconTheme: MaterialStateProperty.resolveWith((states) {
            if (states.contains(MaterialState.selected)) {
              // Color WHEN SELECTED
              return IconThemeData(color: colorScheme.primary, size: 26);
            }
            // Color WHEN NOT SELECTED
            return IconThemeData(color: colorScheme.onSurfaceVariant);
          }),

          // Make the SELECTED label use your primary color
          // (This is for future-proofing, as we're hiding labels)
          labelTextStyle: MaterialStateProperty.resolveWith((states) {
            if (states.contains(MaterialState.selected)) {
              return TextStyle(
                  color: colorScheme.primary, // Color WHEN SELECTED
                  fontWeight: FontWeight.w600, // Make it bolder
                  fontSize: 12); // Explicitly set font size
            }
            // Color WHEN NOT SELECTED
            return TextStyle(color: colorScheme.onSurfaceVariant);
          }),
        ),
        // --- END UPGRADE ---
      ),
      home: const AuthWrapper(),
    );
  }
}